version: "3.3"

services:
  frontend:
    build:
      context: ng-app
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  webapi:
    build:
      context: WebApi
      dockerfile: Dockerfile
    ports:
      - "8001:80"
